Vagrant.configure("2") do |config|
  # Используем последний LTS Ubuntu (22.04 на момент написания)
  config.vm.box = "ubuntu/jammy64"
  
  # Настройки виртуальной машины
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"  # 2GB RAM для комфортной работы
    vb.cpus = 2         # 2 CPU ядра
  end
  
  # Проброс портов для доступа к сервисам
  config.vm.network "forwarded_port", guest: 8123, host: 8123  # ClickHouse HTTP
  config.vm.network "forwarded_port", guest: 9000, host: 9000  # ClickHouse native
  config.vm.network "forwarded_port", guest: 3000, host: 3000  # Grafana
  
  # Provisioning с Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.verbose = "v"
  end
end