---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install basic packages
  apt:
    name: ['curl', 'wget', 'git', 'software-properties-common', 'ufw']
    state: present

- name: Create root user with password
  user:
    name: root
    password: "{{ 'root' | password_hash('sha512') }}"

- name: Create admin user with password and sudo
  user:
    name: admin
    password: "{{ 'admin' | password_hash('sha512') }}"
    groups: sudo
    append: yes
    shell: /bin/bash

- name: Configure UFW (firewall)
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - 22 # SSH
    - 8123 # ClickHouse HTTP
    - 3000 # Grafana
