version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - '8123:8123' # HTTP interface
      - '9000:9000' # Native protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse # Сохраняем данные
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=ch_user # Конкретный пользователь
      - CLICKHOUSE_PASSWORD=ch_pass # Конкретный пароль
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=grafana_admin # Конкретный пользователь
      - GF_SECURITY_ADMIN_PASSWORD=grafana_pass # Конкретный пароль
    depends_on:
      - clickhouse
    restart: unless-stopped

volumes:
  clickhouse_data:
  grafana_data:
