---
- name: Copy docker-compose.yml
  copy:
    src: ../../../docker-compose.yml
    dest: /home/admin/clickhouse-grafana/docker-compose.yml
    owner: admin
    group: admin
    mode: '0644'

- name: Ensure directory exists
  file:
    path: /home/admin/clickhouse-grafana
    state: directory
    owner: admin
    group: admin

- name: Start ClickHouse and Grafana with Docker Compose
  community.docker.docker_compose:
    project_src: /home/admin/clickhouse-grafana
    pull: yes
    build: no
    state: present
  become: yes
  become_user: admin
